# Generated by Django 3.2.5 on 2021-07-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='connection_number',
            field=models.IntegerField(default=0),
        ),
    ]
